### ISSUE TITLE
Do some more tests on Linux

### ISSUE THREAD

**Issue by sourcebox** [sourcebox/tooro-editor#1]
Currently, I don't have a Linux machine that fulfills the graphics requirement of OpenGL ES3. Therefore I can't do any testing on that. I can compile the application on my older machine, but it does not run. Neither does the created AppImage on another machine. It seems to lack some dependencies included, which ones have to be found out.

**Comment by sourcebox** [comment]
I added an AppImage as well as a deb package to the releases that were created by the GitHub CI using the ubuntu-18.04 image. These can now be downloaded and tested.

**Comment by Marzac** [comment]
Ok, I'll talk about the binaries on a KS update.

I mean, I get almost no feedback about the editor but also the machine. But it sales very well. So either people use it and it works or they don't use it. No idea.

I'm a bit frustrated right now as there is no visible reaction from users and future buyers on the net. The Zekit communication didn't generate visible traction. I know I must wait for when I'll open the store but it's a bit ... meh!

Fred


On 12 September 2021 11:18:45 CEST, Oliver Rockstedt ***@***.***> wrote:
>I added an AppImage as well as a deb package to the releases that were created by the GitHub CI using the ubuntu-18.04 image. These can now be downloaded and tested.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/sourcebox/tooro-editor/issues/1#issuecomment-917598209

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by sourcebox** [comment]
Thanks to helpful user @geom3trik it can be stated that the AppImage works.

**Comment by sourcebox** [comment]
After some updates of the `iced` framework, Linux support can be regarded as stable enough for most systems. I did some tests on an old HP EliteBook 2540p, this wasn't working when the app was initially released but now does.
